INSERT INTO data_lineage
(id,timestamp,cluster,current_db, target_table_type,target_table_temporary,predicate,pruning,sql_query,sql_type,owner, workflow_file_name,job_id,user_ip_addr,predicate_str,source_db_name,source_tb_name,source_field_name,source_field_type,source_field_comment,target_db_name,target_tb_name,target_field_name,target_field_type,target_field_comment)
VALUES
(1,'2017-10-19T20:05:02.396','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.categoryname, t3.RegionName\nfrom sales t1, sales_category t2, sales_region t3\nwhere t1.Category = t2.Category\nand t1.Region = t3.Region','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales','orderdate','timestamp',null,'default','sales_joined','orderdate','timestamp',null),
(2,'2017-10-19T20:05:02.396','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.categoryname, t3.RegionName\nfrom sales t1, sales_category t2, sales_region t3\nwhere t1.Category = t2.Category\nand t1.Region = t3.Region','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales','category','string',null,'default','sales_joined','category','string',null),
(3,'2017-10-19T20:05:02.396','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.categoryname, t3.RegionName\nfrom sales t1, sales_category t2, sales_region t3\nwhere t1.Category = t2.Category\nand t1.Region = t3.Region','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales','region','string',null,'default','sales_joined','region','string',null),
(4,'2017-10-19T20:05:02.396','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.categoryname, t3.RegionName\nfrom sales t1, sales_category t2, sales_region t3\nwhere t1.Category = t2.Category\nand t1.Region = t3.Region','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales','orderid','string',null,'default','sales_joined','orderid','string',null),
(5,'2017-10-19T20:05:02.396','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.categoryname, t3.RegionName\nfrom sales t1, sales_category t2, sales_region t3\nwhere t1.Category = t2.Category\nand t1.Region = t3.Region','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales_category','categoryname','string',null,'default','sales_joined','categoryname','string',null),
(6,'2017-10-19T20:05:02.396','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.categoryname, t3.RegionName\nfrom sales t1, sales_category t2, sales_region t3\nwhere t1.Category = t2.Category\nand t1.Region = t3.Region','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales_region','regionname','string',null,'default','sales_joined','regionname','string',null),
(7,'2017-10-29T20:06:17.700','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined2\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.city, t3.categoryname\nfrom sales_joined t1, sales t2, sales_category t3\nwhere t1.orderid = t2.orderid\nand t1.category = t3.category\nand t1.region = South','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales_joined','orderdate','timestamp',null,'default','sales_joined2','orderdate','timestamp',null),
(8,'2017-10-29T20:06:17.700','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined2\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.city, t3.categoryname\nfrom sales_joined t1, sales t2, sales_category t3\nwhere t1.orderid = t2.orderid\nand t1.category = t3.category\nand t1.region = South','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales_joined','category','string',null,'default','sales_joined2','category','string',null),
(9,'2017-10-29T20:06:17.700','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined2\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.city, t3.categoryname\nfrom sales_joined t1, sales t2, sales_category t3\nwhere t1.orderid = t2.orderid\nand t1.category = t3.category\nand t1.region = South','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales_joined','region','string',null,'default','sales_joined2','region','string',null),
(10,'2017-10-29T20:06:17.700','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined2\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.city, t3.categoryname\nfrom sales_joined t1, sales t2, sales_category t3\nwhere t1.orderid = t2.orderid\nand t1.category = t3.category\nand t1.region = South','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales_joined','orderid','string',null,'default','sales_joined2','orderid','string',null),
(11,'2017-10-29T20:06:17.700','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined2\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.city, t3.categoryname\nfrom sales_joined t1, sales t2, sales_category t3\nwhere t1.orderid = t2.orderid\nand t1.category = t3.category\nand t1.region = South','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales','city','string',null,'default','sales_joined2','city','string',null),
(12,'2017-10-29T20:06:17.700','collector','default','MANAGED_TABLE',false,false,false,'create table sales_joined2\nAS\nselect t1.OrderDate, t1.category, t1.region, t1.orderid, t2.city, t3.categoryname\nfrom sales_joined t1, sales t2, sales_category t3\nwhere t1.orderid = t2.orderid\nand t1.category = t3.category\nand t1.region = South','CREATETABLE_AS_SELECT','sohncw',null,null,null,null,'default','sales_category','categoryname','string',null,'default','sales_joined2','categoryname','string',null);

INSERT INTO data_lineage_workflow
(id, workflow_id, name, shape_id, task_id, task_name, task_content, task_file, task_hadoop, task_type, task_description)
VALUES
(0, '2','workflow name2','12','3','sqoop task1(none)','{\"query\":\"select * from titles where $CONDITIONS\",\"taskCnt\":\"1\",\"splitby\":\"key1\",\"interType\":\"FILE\",\"interPath\":\"none-file-path\",\"args\":[\"args1\"],\"delList\":[\"aa\"],\"mkList\":[\"bb\"]}',NULL,NULL,'SQOOP','sqoop desc'),
(1,'2','workflow name2','13','4','sqoop task2(hive)','{\"query\" : \"select * from titles where $CONDITIONS\", \"taskCnt\" : \"4\", \"splitby\" : \"emp_no\"}',NULL,NULL,'SQOOP','sqoop desc'),
(2,'3','workflow name3','14','5','jdbc task1','{\"main-class\":\"\", \"args\":[\"select * from employees\",\"/home/meta/em.csv\",\"=====\"]}',NULL,NULL,'JDBC','task desc'),
(3,'3','workflow name3','15','6','jdbc task2','{\"main-class\":\"com.skt.metatron.JdbcQuery\", \"args\":[\"select * from employees\", \"/home/meta/em.csv\", \"=====\"], \"java-opts\": \"option string\", \"delList\":[\"string\"], \"mkList\":[\"string\"]}',NULL,NULL,'JDBC','task desc'),
(4,'4','workflow name4','16','7','java task1','{\"main-class\":\"main 클래스 이름\", \"args\":[\"string\",\"string\"], \"java-opts\": \"option string\", \"file\":[\"string\"], \"delList\":[\"string\"], \"mkList\":[\"string\"]}',NULL,NULL,'JAVA','task desc'),
(5,'4','workflow name4','17','8','java task2','{\"main-class\":\"main 클래스 이름\", \"args\":[\"string\",\"string\"], \"java-opts\": \"option string\"}',NULL,NULL,'JAVA','task desc'),
(6,'5','workflow name5','18','9','mr task1','{\"configuration\":[{\"name\":\"mapred.job.queue.name\", \"value\":\"default\"},{\"name\":\"mapreduce.mapper.class\", \"value\":\"Map\"},{\"name\":\"mapreduce.reducer.class\", \"value\":\"Reduce\"},{\"name\":\"mapred.input.dir\", \"value\":\"/user/hadoop/sample\"},{\"name\":\"mapred.output.dir\", \"value\":\"/user/hadoop/output/wordcount\"}], \"file\":[\"/workflow/7/WordCount.jar\"]}',NULL,NULL,'MR','task desc'),
(7,'5','workflow name5','19','10','mr task2','{\"configuration\":[{\"name\":\"mapred.job.queue.name\", \"value\":\"default\"}], \"file\":[\"/workflow/7/WordCount.jar\"]}',NULL,NULL,'MR','task desc'),
(8,'6','workflow name6','20','11','exec task1','{\"exec\":\"getHostname.py\",\"args\": [\"111\"],\"file\":[\"/workflow/5/getHostname.py\"], \"delList\":[\"string\"], \"mkList\":[\"string\"]}',NULL,NULL,'EXEC','task desc'),
(9,'6','workflow name6','21','12','exec task2','{\"exec\":\"getHostname.py\",\"args\": [\"111\",\"222\",\"333\"],\"file\":[\"/workflow/5/getHostname.py\"]}',NULL,NULL,'EXEC','task desc'),
(10,'7','workflow name7','22','13','hive task1(script)','{\"script\":\"script.q\", \"param\":[\"string\"], \"args\":[\"string\"], \"file\":[\"string\"], \"delList\":[\"string\"], \"mkList\":[\"string\"]}',NULL,NULL,'HIVE','task desc'),
(11,'7','workflow name7','23','14','hive task2(query)','{\"query\":\"use default\", \"param\":[\"string\"], \"args\":[\"string\"], \"delList\":[\"string\"], \"mkList\":[\"string\"]}',NULL,NULL,'HIVE','task desc'),
(12,'8','workflow name8','24','15','sub_workflow task1','{\"workflow_id\":\"3\",\"configuration\":[{\"name\":\"mapred.job.queue.name\", \"value\":\"default\"}],\"delList\":[],\"mkList\":[]}',NULL,NULL,'SUBWORKFLOW','task desc'),
(13,'8','workflow name8','25','16','sub_workflow task2','{\"workflow_id\":\"2\",\"configuration\":[],\"delList\":[],\"mkList\":[]}',NULL,NULL,'SUBWORKFLOW','task desc'),
(14,'9','workflow name9','26','17','ssh task1','{\"host\":\"aaa@210.211.110.46\",\"command\":\"getHostname.py\",\"args\": [\"111\"]}',NULL,NULL,'SSH','task desc'),
(15,'9','workflow name9','27','18','ssh task2','{\"host\":\"bbb@210.211.110.47\",\"command\":\"getHostname.py\",\"args\": [\"111\"],\"delList\":[\"de1\"],\"mkList\":[\"mk1\"]}',NULL,NULL,'SSH','task desc'),
(16,'c57a52e6-9605-4869-aea8-aee47535930d','get Hostname','04e6b383-af14-41e8-8cbf-2ddc739a6f6e','9b71f914-9959-4bd9-b790-78fe3bbfddf6','get Hostname','{\"exec\":\"getHostname.py\",\"file\":[\"/workflow/ext_script/getHostname.py\"],\"args\":[],\"delList\":[],\"mkList\":[]}',NULL,NULL,'EXEC','get host name'),
(17,'e009031f-4684-4052-b1cb-43a2ee0bab55','migration employees database','169df4e4-7efe-40d5-8e5c-2acca591eaf6','143e8a83-a52c-4ada-a584-960cf482db42','migration employees table ','{\"query\":\"select * from employees where $CONDITIONS\",\"taskCnt\":\"1\",\"splitby\":\"emp_no\",\"args\":[],\"delList\":[],\"mkList\":[]}',NULL,NULL,'SQOOP','migration employees table from demo-collect to HIVE'),
(18,'e009031f-4684-4052-b1cb-43a2ee0bab55','migration employees database','6205890a-2ac9-47c5-aef2-f6d8db702f6d','c691c48b-83c8-46d1-866d-618afbed6c3c','migration titles table','{\"query\":\"select * from titles where $CONDITIONS\",\"taskCnt\":\"1\",\"splitby\":\"emp_no\",\"args\":[],\"delList\":[],\"mkList\":[]}',NULL,NULL,'SQOOP','migration titles table from demo-collector to HIVE'),
(19,'e009031f-4684-4052-b1cb-43a2ee0bab55','migration employees database','d5207857-44f8-45bb-b11d-f2bb578d2ff6','9b71f914-9959-4bd9-b790-78fe3bbfddf6','get Hostname','{\"exec\":\"getHostname.py\",\"file\":[\"/workflow/ext_script/getHostname.py\"],\"args\":[],\"delList\":[],\"mkList\":[]}',NULL,NULL,'EXEC','get host name');

INSERT INTO data_lineage_table(id,col_name,comment,data_type,info_type,schema_name,table_name) VALUES
(0, 'orderdate', '', 'timestamp', 'COLUMN', 'default', 'sales'),
(1, 'category', '', 'string', 'COLUMN', 'default', 'sales'),
(2, 'city', '', 'string', 'COLUMN', 'default', 'sales'),
(3, 'country', '', 'string', 'COLUMN', 'default', 'sales'),
(4, 'customername', '', 'string', 'COLUMN', 'default', 'sales'),
(5, 'orderid', '', 'string', 'COLUMN', 'default', 'sales'),
(6, 'postalcode', '', 'string', 'COLUMN', 'default', 'sales'),
(7, 'productname', '', 'string', 'COLUMN', 'default', 'sales'),
(8, 'quantity', '', 'string', 'COLUMN', 'default', 'sales'),
(9, 'region', '', 'string', 'COLUMN', 'default', 'sales'),
(10, 'segment', '', 'string', 'COLUMN', 'default', 'sales'),
(11, 'shipdate', '', 'string', 'COLUMN', 'default', 'sales'),
(12, 'shipmode', '', 'string', 'COLUMN', 'default', 'sales'),
(13, 'state', '', 'string', 'COLUMN', 'default', 'sales'),
(14, 'sub-category', '', 'string', 'COLUMN', 'default', 'sales'),
(15, 'shipstatus', '', 'string', 'COLUMN', 'default', 'sales'),
(16, 'orderprofitable', '', 'string', 'COLUMN', 'default', 'sales'),
(17, 'salesabovetarget', '', 'string', 'COLUMN', 'default', 'sales'),
(18, 'latitude', '', 'string', 'COLUMN', 'default', 'sales'),
(19, 'longitude', '', 'string', 'COLUMN', 'default', 'sales'),
(20, 'discount', '', 'double', 'COLUMN', 'default', 'sales'),
(21, 'profit', '', 'double', 'COLUMN', 'default', 'sales'),
(22, 'sales', '', 'double', 'COLUMN', 'default', 'sales'),
(23, 'daystoshipactual', '', 'double', 'COLUMN', 'default', 'sales'),
(24, 'salesforecast', '', 'double', 'COLUMN', 'default', 'sales'),
(25, 'daystoshipscheduled', '', 'double', 'COLUMN', 'default', 'sales'),
(26, 'salespercustomer', '', 'double', 'COLUMN', 'default', 'sales'),
(27, 'profitratio', '', 'double', 'COLUMN', 'default', 'sales'),
(28, '# Detailed Table Information', 'null', 'null', 'DETAILED', 'default', 'sales'),
(29, 'Database:', 'null', 'default', 'DETAILED', 'default', 'sales'),
(30, 'Owner:', 'null', 'sohncw', 'DETAILED', 'default', 'sales'),
(31, 'CreateTime:', 'null', 'Mon Jul 24 09:51:17 KST 2017', 'DETAILED', 'default', 'sales'),
(32, 'LastAccessTime:', 'null', 'UNKNOWN', 'DETAILED', 'default', 'sales'),
(33, 'Protect Mode:', 'null', 'None', 'DETAILED', 'default', 'sales'),
(34, 'Retention:', 'null', '0', 'DETAILED', 'default', 'sales'),
(35, 'Location:', 'null', 'hdfs://localhost:9000/user/hive/warehouse/sales', 'DETAILED', 'default', 'sales'),
(36, 'Table Type:', 'null', 'MANAGED_TABLE', 'DETAILED', 'default', 'sales'),
(37, 'Table Parameters:', 'null', 'null', 'DETAILED', 'default', 'sales'),
(38, '', 'false', 'COLUMN_STATS_ACCURATE', 'DETAILED', 'default', 'sales'),
(39, '', '123', 'comment', 'DETAILED', 'default', 'sales'),
(40, '', 'sohncw', 'last_modified_by', 'DETAILED', 'default', 'sales'),
(41, '', '1508289564', 'last_modified_time', 'DETAILED', 'default', 'sales'),
(42, '', '1', 'numFiles', 'DETAILED', 'default', 'sales'),
(43, '', '-1', 'numRows', 'DETAILED', 'default', 'sales'),
(44, '', '-1', 'rawDataSize', 'DETAILED', 'default', 'sales'),
(45, '', '2731122', 'totalSize', 'DETAILED', 'default', 'sales'),
(46, '', '1508289564', 'transient_lastDdlTime', 'DETAILED', 'default', 'sales'),
(47, '# Storage Information', 'null', 'null', 'STORAGE', 'default', 'sales'),
(48, 'SerDe Library:', 'null', 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe', 'STORAGE', 'default', 'sales'),
(49, 'InputFormat:', 'null', 'org.apache.hadoop.mapred.TextInputFormat', 'STORAGE', 'default', 'sales'),
(50, 'OutputFormat:', 'null', 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat', 'STORAGE', 'default', 'sales'),
(51, 'Compressed:', 'null', 'No', 'STORAGE', 'default', 'sales'),
(52, 'Num Buckets:', 'null', '-1', 'STORAGE', 'default', 'sales'),
(53, 'Bucket Columns:', 'null', '[]', 'STORAGE', 'default', 'sales'),
(54, 'Sort Columns:', 'null', '[]', 'STORAGE', 'default', 'sales'),
(55, 'Storage Desc Params:', 'null', 'null', 'STORAGE', 'default', 'sales'),
(56, '', '\t', 'field.delim', 'STORAGE', 'default', 'sales'),
(57, '', '\t', 'serialization.format', 'STORAGE', 'default', 'sales'),
(58, 'created', '', 'timestamp', 'COLUMN', 'default', 'sales_category'),
(59, 'category', '', 'string', 'COLUMN', 'default', 'sales_category'),
(60, 'categoryname', '', 'string', 'COLUMN', 'default', 'sales_category'),
(61, 'categorycode', '', 'string', 'COLUMN', 'default', 'sales_category'),
(62, '# Detailed Table Information', 'null', 'null', 'DETAILED', 'default', 'sales_category'),
(63, 'Database:', 'null', 'default', 'DETAILED', 'default', 'sales_category'),
(64, 'Owner:', 'null', 'sohncw', 'DETAILED', 'default', 'sales_category'),
(65, 'CreateTime:', 'null', 'Wed Oct 25 09:10:51 KST 2017', 'DETAILED', 'default', 'sales_category'),
(66, 'LastAccessTime:', 'null', 'UNKNOWN', 'DETAILED', 'default', 'sales_category'),
(67, 'Protect Mode:', 'null', 'None', 'DETAILED', 'default', 'sales_category'),
(68, 'Retention:', 'null', '0', 'DETAILED', 'default', 'sales_category'),
(69, 'Location:', 'null', 'hdfs://localhost:9000/user/hive/warehouse/sales_category', 'DETAILED', 'default', 'sales_category'),
(70, 'Table Type:', 'null', 'MANAGED_TABLE', 'DETAILED', 'default', 'sales_category'),
(71, 'Table Parameters:', 'null', 'null', 'DETAILED', 'default', 'sales_category'),
(72, '', 'true', 'COLUMN_STATS_ACCURATE', 'DETAILED', 'default', 'sales_category'),
(73, '', '1', 'numFiles', 'DETAILED', 'default', 'sales_category'),
(74, '', '0', 'numRows', 'DETAILED', 'default', 'sales_category'),
(75, '', '0', 'rawDataSize', 'DETAILED', 'default', 'sales_category'),
(76, '', '130', 'totalSize', 'DETAILED', 'default', 'sales_category'),
(77, '', '1508890251', 'transient_lastDdlTime', 'DETAILED', 'default', 'sales_category'),
(78, '# Storage Information', 'null', 'null', 'STORAGE', 'default', 'sales_category'),
(79, 'SerDe Library:', 'null', 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe', 'STORAGE', 'default', 'sales_category'),
(80, 'InputFormat:', 'null', 'org.apache.hadoop.mapred.TextInputFormat', 'STORAGE', 'default', 'sales_category'),
(81, 'OutputFormat:', 'null', 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat', 'STORAGE', 'default', 'sales_category'),
(82, 'Compressed:', 'null', 'No', 'STORAGE', 'default', 'sales_category'),
(83, 'Num Buckets:', 'null', '-1', 'STORAGE', 'default', 'sales_category'),
(84, 'Bucket Columns:', 'null', '[]', 'STORAGE', 'default', 'sales_category'),
(85, 'Sort Columns:', 'null', '[]', 'STORAGE', 'default', 'sales_category'),
(86, 'Storage Desc Params:', 'null', 'null', 'STORAGE', 'default', 'sales_category'),
(87, '', ',', 'field.delim', 'STORAGE', 'default', 'sales_category'),
(88, '', ',', 'serialization.format', 'STORAGE', 'default', 'sales_category'),
(89, 'created', '', 'timestamp', 'COLUMN', 'default', 'sales_region'),
(90, 'region', '', 'string', 'COLUMN', 'default', 'sales_region'),
(91, 'regionname', '', 'string', 'COLUMN', 'default', 'sales_region'),
(92, '# Detailed Table Information', 'null', 'null', 'DETAILED', 'default', 'sales_region'),
(93, 'Database:', 'null', 'default', 'DETAILED', 'default', 'sales_region'),
(94, 'Owner:', 'null', 'sohncw', 'DETAILED', 'default', 'sales_region'),
(95, 'CreateTime:', 'null', 'Wed Oct 25 09:10:51 KST 2017', 'DETAILED', 'default', 'sales_region'),
(96, 'LastAccessTime:', 'null', 'UNKNOWN', 'DETAILED', 'default', 'sales_region'),
(97, 'Protect Mode:', 'null', 'None', 'DETAILED', 'default', 'sales_region'),
(98, 'Retention:', 'null', '0', 'DETAILED', 'default', 'sales_region'),
(99, 'Location:', 'null', 'hdfs://localhost:9000/user/hive/warehouse/sales_region', 'DETAILED', 'default', 'sales_region'),
(100, 'Table Type:', 'null', 'MANAGED_TABLE', 'DETAILED', 'default', 'sales_region'),
(101, 'Table Parameters:', 'null', 'null', 'DETAILED', 'default', 'sales_region'),
(102, '', 'true', 'COLUMN_STATS_ACCURATE', 'DETAILED', 'default', 'sales_region'),
(103, '', '1', 'numFiles', 'DETAILED', 'default', 'sales_region'),
(104, '', '0', 'numRows', 'DETAILED', 'default', 'sales_region'),
(105, '', '0', 'rawDataSize', 'DETAILED', 'default', 'sales_region'),
(106, '', '131', 'totalSize', 'DETAILED', 'default', 'sales_region'),
(107, '', '1508890252', 'transient_lastDdlTime', 'DETAILED', 'default', 'sales_region'),
(108, '# Storage Information', 'null', 'null', 'STORAGE', 'default', 'sales_region'),
(109, 'SerDe Library:', 'null', 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe', 'STORAGE', 'default', 'sales_region'),
(110, 'InputFormat:', 'null', 'org.apache.hadoop.mapred.TextInputFormat', 'STORAGE', 'default', 'sales_region'),
(111, 'OutputFormat:', 'null', 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat', 'STORAGE', 'default', 'sales_region'),
(112, 'Compressed:', 'null', 'No', 'STORAGE', 'default', 'sales_region'),
(113, 'Num Buckets:', 'null', '-1', 'STORAGE', 'default', 'sales_region'),
(114, 'Bucket Columns:', 'null', '[]', 'STORAGE', 'default', 'sales_region'),
(115, 'Sort Columns:', 'null', '[]', 'STORAGE', 'default', 'sales_region'),
(116, 'Storage Desc Params:', 'null', 'null', 'STORAGE', 'default', 'sales_region'),
(117, '', ',', 'field.delim', 'STORAGE', 'default', 'sales_region'),
(118, '', ',', 'serialization.format', 'STORAGE', 'default', 'sales_region'),
(119, 'orderdate', '', 'timestamp', 'COLUMN', 'default', 'sales_joined'),
(120, 'category', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(121, 'city', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(122, 'country', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(123, 'customername', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(124, 'orderid', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(125, 'postalcode', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(126, 'productname', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(127, 'quantity', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(128, 'region', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(129, 'segment', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(130, 'shipdate', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(131, 'shipmode', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(132, 'state', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(133, 'sub-category', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(134, 'shipstatus', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(135, 'orderprofitable', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(136, 'salesabovetarget', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(137, 'latitude', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(138, 'longitude', '', 'string', 'COLUMN', 'default', 'sales_joined'),
(139, 'discount', '', 'double', 'COLUMN', 'default', 'sales_joined'),
(140, 'profit', '', 'double', 'COLUMN', 'default', 'sales_joined'),
(141, 'sales', '', 'double', 'COLUMN', 'default', 'sales_joined'),
(142, 'daystoshipactual', '', 'double', 'COLUMN', 'default', 'sales_joined'),
(143, 'salesforecast', '', 'double', 'COLUMN', 'default', 'sales_joined'),
(144, 'daystoshipscheduled', '', 'double', 'COLUMN', 'default', 'sales_joined'),
(145, 'salespercustomer', '', 'double', 'COLUMN', 'default', 'sales_joined'),
(146, 'profitratio', '', 'double', 'COLUMN', 'default', 'sales_joined'),
(147, '# Detailed Table Information', 'null', 'null', 'DETAILED', 'default', 'sales_joined'),
(148, 'Database:', 'null', 'default', 'DETAILED', 'default', 'sales_joined'),
(149, 'Owner:', 'null', 'sohncw', 'DETAILED', 'default', 'sales_joined'),
(150, 'CreateTime:', 'null', 'Mon Jul 24 09:51:17 KST 2017', 'DETAILED', 'default', 'sales_joined'),
(151, 'LastAccessTime:', 'null', 'UNKNOWN', 'DETAILED', 'default', 'sales_joined'),
(152, 'Protect Mode:', 'null', 'None', 'DETAILED', 'default', 'sales_joined'),
(153, 'Retention:', 'null', '0', 'DETAILED', 'default', 'sales_joined'),
(154, 'Location:', 'null', 'hdfs://localhost:9000/user/hive/warehouse/sales', 'DETAILED', 'default', 'sales_joined'),
(155, 'Table Type:', 'null', 'MANAGED_TABLE', 'DETAILED', 'default', 'sales_joined'),
(156, 'Table Parameters:', 'null', 'null', 'DETAILED', 'default', 'sales_joined'),
(157, '', 'false', 'COLUMN_STATS_ACCURATE', 'DETAILED', 'default', 'sales_joined'),
(158, '', '123', 'comment', 'DETAILED', 'default', 'sales_joined'),
(159, '', 'sohncw', 'last_modified_by', 'DETAILED', 'default', 'sales_joined'),
(160, '', '1508289564', 'last_modified_time', 'DETAILED', 'default', 'sales_joined'),
(161, '', '1', 'numFiles', 'DETAILED', 'default', 'sales_joined'),
(162, '', '-1', 'numRows', 'DETAILED', 'default', 'sales_joined'),
(163, '', '-1', 'rawDataSize', 'DETAILED', 'default', 'sales_joined'),
(164, '', '2731122', 'totalSize', 'DETAILED', 'default', 'sales_joined'),
(165, '', '1508289564', 'transient_lastDdlTime', 'DETAILED', 'default', 'sales_joined'),
(166, '# Storage Information', 'null', 'null', 'STORAGE', 'default', 'sales_joined'),
(167, 'SerDe Library:', 'null', 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe', 'STORAGE', 'default', 'sales_joined'),
(168, 'InputFormat:', 'null', 'org.apache.hadoop.mapred.TextInputFormat', 'STORAGE', 'default', 'sales_joined'),
(169, 'OutputFormat:', 'null', 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat', 'STORAGE', 'default', 'sales_joined'),
(170, 'Compressed:', 'null', 'No', 'STORAGE', 'default', 'sales_joined'),
(171, 'Num Buckets:', 'null', '-1', 'STORAGE', 'default', 'sales_joined'),
(172, 'Bucket Columns:', 'null', '[]', 'STORAGE', 'default', 'sales_joined'),
(173, 'Sort Columns:', 'null', '[]', 'STORAGE', 'default', 'sales_joined'),
(174, 'Storage Desc Params:', 'null', 'null', 'STORAGE', 'default', 'sales_joined'),
(175, '', '\t', 'field.delim', 'STORAGE', 'default', 'sales_joined'),
(176, '', '\t', 'serialization.format', 'STORAGE', 'default', 'sales_joined'),
(177, 'orderdate', '', 'timestamp', 'COLUMN', 'default', 'sales_joined2'),
(178, 'category', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(179, 'city', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(180, 'country', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(181, 'customername', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(182, 'orderid', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(183, 'postalcode', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(184, 'productname', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(185, 'quantity', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(186, 'region', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(187, 'segment', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(188, 'shipdate', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(189, 'shipmode', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(190, 'state', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(191, 'sub-category', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(192, 'shipstatus', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(193, 'orderprofitable', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(194, 'salesabovetarget', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(195, 'latitude', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(196, 'longitude', '', 'string', 'COLUMN', 'default', 'sales_joined2'),
(197, 'discount', '', 'double', 'COLUMN', 'default', 'sales_joined2'),
(198, 'profit', '', 'double', 'COLUMN', 'default', 'sales_joined2'),
(199, 'sales', '', 'double', 'COLUMN', 'default', 'sales_joined2'),
(200, 'daystoshipactual', '', 'double', 'COLUMN', 'default', 'sales_joined2'),
(201, 'salesforecast', '', 'double', 'COLUMN', 'default', 'sales_joined2'),
(202, 'daystoshipscheduled', '', 'double', 'COLUMN', 'default', 'sales_joined2'),
(203, 'salespercustomer', '', 'double', 'COLUMN', 'default', 'sales_joined2'),
(204, 'profitratio', '', 'double', 'COLUMN', 'default', 'sales_joined2'),
(205, '# Detailed Table Information', 'null', 'null', 'DETAILED', 'default', 'sales_joined2'),
(206, 'Database:', 'null', 'default', 'DETAILED', 'default', 'sales_joined2'),
(207, 'Owner:', 'null', 'sohncw', 'DETAILED', 'default', 'sales_joined2'),
(208, 'CreateTime:', 'null', 'Mon Jul 24 09:51:17 KST 2017', 'DETAILED', 'default', 'sales_joined2'),
(209, 'LastAccessTime:', 'null', 'UNKNOWN', 'DETAILED', 'default', 'sales_joined2'),
(210, 'Protect Mode:', 'null', 'None', 'DETAILED', 'default', 'sales_joined2'),
(211, 'Retention:', 'null', '0', 'DETAILED', 'default', 'sales_joined2'),
(212, 'Location:', 'null', 'hdfs://localhost:9000/user/hive/warehouse/sales', 'DETAILED', 'default', 'sales_joined2'),
(213, 'Table Type:', 'null', 'MANAGED_TABLE', 'DETAILED', 'default', 'sales_joined2'),
(214, 'Table Parameters:', 'null', 'null', 'DETAILED', 'default', 'sales_joined2'),
(215, '', 'false', 'COLUMN_STATS_ACCURATE', 'DETAILED', 'default', 'sales_joined2'),
(216, '', '123', 'comment', 'DETAILED', 'default', 'sales_joined2'),
(217, '', 'sohncw', 'last_modified_by', 'DETAILED', 'default', 'sales_joined2'),
(218, '', '1508289564', 'last_modified_time', 'DETAILED', 'default', 'sales_joined2'),
(219, '', '1', 'numFiles', 'DETAILED', 'default', 'sales_joined2'),
(220, '', '-1', 'numRows', 'DETAILED', 'default', 'sales_joined2'),
(221, '', '-1', 'rawDataSize', 'DETAILED', 'default', 'sales_joined2'),
(222, '', '2731122', 'totalSize', 'DETAILED', 'default', 'sales_joined2'),
(223, '', '1508289564', 'transient_lastDdlTime', 'DETAILED', 'default', 'sales_joined2'),
(224, '# Storage Information', 'null', 'null', 'STORAGE', 'default', 'sales_joined2'),
(225, 'SerDe Library:', 'null', 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe', 'STORAGE', 'default', 'sales_joined2'),
(226, 'InputFormat:', 'null', 'org.apache.hadoop.mapred.TextInputFormat', 'STORAGE', 'default', 'sales_joined2'),
(227, 'OutputFormat:', 'null', 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat', 'STORAGE', 'default', 'sales_joined2'),
(228, 'Compressed:', 'null', 'No', 'STORAGE', 'default', 'sales_joined2'),
(229, 'Num Buckets:', 'null', '-1', 'STORAGE', 'default', 'sales_joined2'),
(230, 'Bucket Columns:', 'null', '[]', 'STORAGE', 'default', 'sales_joined2'),
(231, 'Sort Columns:', 'null', '[]', 'STORAGE', 'default', 'sales_joined2'),
(232, 'Storage Desc Params:', 'null', 'null', 'STORAGE', 'default', 'sales_joined2'),
(233, '', '\t', 'field.delim', 'STORAGE', 'default', 'sales_joined2'),
(234, '', '\t', 'serialization.format', 'STORAGE', 'default', 'sales_joined2');
