INSERT INTO BOOK(TYPE, ID, CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, VERSION, BOOK_DESC, BOOK_FAVORITE, BOOK_FOLDER_ID, BOOK_NAME, BOOK_TAG, WS_ID) VALUES
('workbook', 'wb-001', 'admin', now(), 'admin', now(), 0, NULL, FALSE, 'ROOT', 'testworkbook', '', 'ws-02');
INSERT INTO BOOK_WORKBOOK(WB_CONF, ID) VALUES('wb-001');
INSERT INTO DATASOURCE_WORKBOOK(BOOK_ID, DS_ID) VALUES('wb-001', 'ds-37');
INSERT INTO PAGE(ID, CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, VERSION, PAGE_CONF, PAGE_DESCRIPTION, PAGE_FAVORITE, PAGE_IMAGE_URL, PAGE_NAME, PAGE_TYPE, PAGE_TAG, BOOK_ID) VALUES
('page-001', 'polaris', now(), 'polaris', now(), 0, '{"type":"sheet","filters":[{"type":"interval","field":"OrderDate","startDate":"2011-01-04T00:00:00.000Z","endDate":"2014-12-31T00:00:00.000Z","relValue":1,"timeUnit":"MINUTES","selector":"RANGE"}],"pivot":{"columns":[{"type":"dimension","fieldName":"Category","alias":"Category","biType":"dimension"}],"rows":[],"aggregations":[{"type":"measure","fieldName":"Sales","alias":"SUM(Sales)","aggregationType":"SUM","biType":"measure"}]},"chart":{"type":"bar","color":{"type":"series","schema":"12colors-1","auto":false},"size":{"size":80,"auto":false},"chartZooms":[{"start":0.0,"end":100.0,"startValue":0.0,"endValue":2.0,"count":0,"orient":"HORIZONTAL"}],"axis":{"min":0.0,"max":0.0,"auto":false},"chartDrawingFlag":true,"label":{"showXAxisLabel":true,"showYAxisLabel":true,"shows":[{"mode":"column","mark":"HORIZONTAL"},{"mode":"row","mark":"HORIZONTAL"}],"auto":false},"legend":{"pos":"TOP","count":5,"auto":false},"series":{"mark":"MULTIPLE","align":"VERTICAL","unit":"NONE"},"baseLine":false},"limit":{"limit":100000}}', 'test', FALSE, 'metatron://images/page/802188d2-682b-4ad2-b507-0740cebffaf1', 'test', 'SHEET', 'default', 'wb-001'),
('page-002', 'polaris', now(), 'polaris', now(), 0, '{"type":"sheet","filters":[{"type":"interval","field":"OrderDate","startDate":"2011-01-04T00:00:00.000Z","endDate":"2014-12-31T00:00:00.000Z","relValue":1,"timeUnit":"MINUTES","selector":"RANGE"}],"pivot":{"columns":[{"type":"timestamp","fieldName":"OrderDate","alias":"OrderDate_MONTH","granularity":"MONTH","biType":"timestamp"}],"rows":[],"aggregations":[{"type":"measure","fieldName":"Sales","alias":"SUM(Sales)","aggregationType":"SUM","biType":"measure"}]},"chart":{"type":"line","color":{"type":"series","schema":"12colors-1","auto":false},"size":{"size":2,"auto":false},"chartZooms":[{"start":59.57446808510638,"end":100.0,"startValue":28.0,"endValue":47.0,"count":0,"orient":"HORIZONTAL"}],"axis":{"min":0.0,"max":0.0,"auto":false},"chartDrawingFlag":true,"label":{"showXAxisLabel":true,"showYAxisLabel":true,"shows":[{"mode":"column","mark":"HORIZONTAL"},{"mode":"row","mark":"HORIZONTAL"}],"auto":false},"legend":{"pos":"TOP","count":5,"auto":false},"series":{"mark":"LINE","hasPoint":false,"hasLine":true,"accumulate":false},"baseLine":false,"trendLine":false},"limit":{"limit":100000,"sort":[{"fieldName":"OrderDate_MONTH","direction":"ASC"}]}}', NULL, FALSE, 'metatron://images/page/b29288a4-1c37-4669-8ead-7ecd7a5c3828', 'Line', 'SHEET', '', 'wb-001'),
('board-001', 'polaris', now(), 'polaris', now(), 0, '{"type":"board","options":{"realtime":{"enabled":false,"interval":0},"showMiniMap":true},"relations":[{"pageRef":"page-001"},{"pageRef":"page-002"}],"layout":{"content":{"type":"column","contents":[{"type":"stack","height":50.0,"contents":[{"type":"component","pageRef":"page-001","showZoom":true,"showLegend":false}]},{"type":"stack","height":50.0,"contents":[{"type":"component","pageRef":"page-002","showZoom":true,"showLegend":false}]}]}}}', NULL, FALSE, 'metatron://images/page/26e9bbb5-6e2d-4aba-ba71-106e32fb217c', 'test workboard', 'BOARD', '', 'wb-001');




