INSERT INTO users(ID, CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, VERSION, USER_EMAIL, USER_FULL_NAME, USER_IMAGE_URL, USER_STATUS, USER_STATUS_MSG, USER_TEL, USER_NAME, USER_PASSWORD) VALUES
('test01', 'admin', now(), 'admin', now(), 0, 'test01@metatron.com', 'TEST_01', NULL, 'ACTIVATED', NULL, NULL, 'test01', 'test01'),
('test02', 'admin', now(), 'admin', now(), 0, 'test01@metatron.com', 'TEST_02', NULL, 'ACTIVATED', NULL, NULL, 'test02', 'test02');

INSERT INTO role_set(ID, CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, VERSION, ROLE_SET_NAME, ROLE_SET_SCOPE, ROLE_SET_LINKED) VALUES
('TEST_PRIVATE_ROLE_SET', 'admin', now(), 'admin', now(), 0, 'TEST_PRIVATE', 'PRIVATE', 0),
('TEST_ROLE_SET', 'admin', now(), 'admin', now(), 0, 'TEST_GENERAL', 'PUBLIC', 1),
('TEST_ROLE_SET_KOR', 'admin', now(), 'admin', now(), 0, '테스트 롤셋', 'PUBLIC', 0),
('TEST_CUSTOM_ROLE_SET', 'admin', now(), 'admin', now(), 0, '테스트 커스텀 롤셋', 'PUBLIC', 1);

INSERT INTO roles(ID, CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, VERSION, ROLE_DESC, ROLE_NAME, ROLE_PREDEFINED, ROLE_SCOPE, ROLE_IS_ADMIN, ROLE_IS_DEFAULT, ROLE_SET_ID) VALUES
('ROLE_WORKSPACE_TEST_ADMIN', 'admin', now(), 'admin', now(), 0, NULL, 'WORKSPACE_TEST_ADMIN', TRUE, 'WORKSPACE', FALSE, FALSE, 'TEST_ROLE_SET'),
('ROLE_WORKSPACE_TEST_EDITOR', 'admin', now(), 'admin', now(), 0, NULL, 'WORKSPACE_TEST_EDITOR', TRUE, 'WORKSPACE', FALSE, FALSE, 'TEST_ROLE_SET'),
('ROLE_WORKSPACE_TEST_VIEWER', 'admin', now(), 'admin', now(), 0, NULL, 'WORKSPACE_TEST_VIEWER', TRUE, 'WORKSPACE', FALSE, TRUE, 'TEST_ROLE_SET'),
('ROLE_WORKSPACE_TEST_VIEWER_KOR', 'admin', now(), 'admin', now(), 0, NULL, 'WORKSPACE_TEST_VIEWER_KOR', TRUE, 'WORKSPACE', FALSE , TRUE, 'TEST_ROLE_SET_KOR'),
('ROLE_WORKSPACE_TEST_EDITOR_KOR', 'admin', now(), 'admin', now(), 0, NULL, 'WORKSPACE_TEST_EDITOR_KOR', TRUE, 'WORKSPACE', FALSE, FALSE, 'TEST_ROLE_SET_KOR'),
('ROLE_WORKSPACE_TEST_CUSTOM_V1', 'admin', now(), 'admin', now(), 0, NULL, 'WORKSPACE_TEST_CUSTOM_V1', TRUE, 'WORKSPACE', FALSE, TRUE, 'TEST_CUSTOM_ROLE_SET'),
('ROLE_WORKSPACE_TEST_CUSTOM_V2', 'admin', now(), 'admin', now(), 0, NULL, 'WORKSPACE_TEST_CUSTOM_V2', TRUE, 'WORKSPACE', NULL, NULL, 'TEST_CUSTOM_ROLE_SET');

INSERT INTO role_perm(ROLE_ID, PERM_ID) VALUES
('ROLE_WORKSPACE_TEST_CUSTOM_V1', 100011),
('ROLE_WORKSPACE_TEST_CUSTOM_V2', 100012),
('ROLE_WORKSPACE_TEST_CUSTOM_V2', 100013),
('ROLE_WORKSPACE_TEST_VIEWER', 100012),
('ROLE_WORKSPACE_TEST_EDITOR', 100014),
('ROLE_WORKSPACE_TEST_EDITOR', 100015),
('ROLE_WORKSPACE_TEST_EDITOR', 100018),
('ROLE_WORKSPACE_TEST_VIEWER_KOR', 100019),
('ROLE_WORKSPACE_TEST_EDITOR_KOR', 100020),
('ROLE_WORKSPACE_TEST_EDITOR_KOR', 100019),
('ROLE_WORKSPACE_TEST_EDITOR_KOR', 100018),
('ROLE_WORKSPACE_TEST_ADMIN', 100010),
('ROLE_WORKSPACE_TEST_ADMIN', 100011),
('ROLE_WORKSPACE_TEST_ADMIN', 100014),
('ROLE_WORKSPACE_TEST_ADMIN', 100017),
('ROLE_WORKSPACE_TEST_ADMIN', 100020);

INSERT INTO workspace(id, ws_name, ws_owner_id, ws_pub_type, ws_desc, version, created_time, created_by, modified_time, modified_by) VALUES
('ws-test-01', 'TEST Workspace', 'admin', 'SHARED', '', 1.0, NOW(), 'admin',  NOW(), 'admin');

INSERT INTO role_set_workspace(RS_ID, WS_ID) VALUES
('TEST_ROLE_SET', 'ws-test-01'),
('TEST_CUSTOM_ROLE_SET', 'ws-test-01');

INSERT INTO workspace_member(id, member_id, member_type, member_role, ws_id) VALUES
(500001, 'admin', 'USER', 'WORKSPACE_TEST_VIEWER', 'ws-test-01'),
(500002, 'metatron', 'USER', 'WORKSPACE_TEST_EDITOR', 'ws-test-01'),
(500003, 'test01', 'USER', 'WORKSPACE_TEST_ADMIN', 'ws-test-01'),
(500004, 'test02', 'USER', 'WORKSPACE_TEST_CUSTOM_V2', 'ws-test-01');

COMMIT;
