INSERT INTO configuration(ID, CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, VERSION, CONF_DOMAIN, CONF_PROFILE, CONF_TYPE, CONF_SPEC) VALUES
('default-bar-chart-001', 'admin', now(), 'admin', now(), 0, 'CHART', 'tango', 'bar', '{"type":"bar","color":{"type":"dimension","schema":"5colors-1"},"size":{"size":80},"label":{"scaled":false,"showValue":false,"axis":[{"mode":"row","showName":false,"name":"","showMark":true,"mark":"HORIZONTAL"},{"mode":"column","showName":false,"name":"","showMark":true,"mark":"HORIZONTAL"}]},"axis":{"auto":false},"legend":{"pos":"TOP","auto":true,"count":5},"series":{"mark":"MULTIPLE","align":"VERTICAL","unit":"NONE","view":"ALL"},"baseLine":false}');

INSERT INTO configuration(ID, CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, VERSION, CONF_DOMAIN, CONF_PROFILE, CONF_TYPE, CONF_SPEC) VALUES
('default-grid-chart-001', 'admin', now(), 'admin', now(), 0, 'CHART', 'tango', 'grid', '{"type":"grid","color":{"type":"cell","mode":"LINEAR","mark":"BACKGROUND"},"size":{"size":12},"align":{"hAlign":"LEFT","vAlign":"CENTER"},"series":{"dataType":"PIVOT","layout":"HORIZONTAL"}}');

INSERT INTO configuration(ID, CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, VERSION, CONF_DOMAIN, CONF_PROFILE, CONF_TYPE, CONF_SPEC) VALUES
('default-line-chart-001', 'admin', now(), 'admin', now(), 0, 'CHART', 'tango', 'line', '{"type":"line","color":{"type":"dimension","schema":"5colors-1"},"size":{"size":2},"label":{"showValue":false,"axis":[{"mode":"row","showName":false,"name":"","showMark":true,"mark":"HORIZONTAL"},{"mode":"column","showName":false,"name":"","showMark":true,"mark":"HORIZONTAL"}]},"axis":{"auto":false},"legend":{"pos":"TOP","auto":true,"count":5},"series":{"mark":"LINE","hasPoint":false,"hasLine":true,"accumulate":false},"baseLine":false}');

INSERT INTO configuration(ID, CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, VERSION, CONF_DOMAIN, CONF_PROFILE, CONF_TYPE, CONF_SPEC) VALUES
('default-scatter-chart-001', 'admin', now(), 'admin', now(), 0, 'CHART', 'tango', 'scatter', '{"type":"scatter","color":{"type":"dimension","schema":"5colors-1"},"size":{"size":13},"label":{"scaled":false,"showValue":false,"axis":[{"mode":"row","showName":false,"name":"","showMark":true,"mark":"HORIZONTAL"},{"mode":"column","showName":false,"name":"","showMark":true,"mark":"HORIZONTAL"}]},"axis":{"auto":false},"legend":{"pos":"TOP","auto":true,"count":5},"series":{"mark":"SINGLE","shape":"CIRCLE"},"baseLine":false}');

INSERT INTO configuration(ID, CREATED_BY, CREATED_TIME, MODIFIED_BY, MODIFIED_TIME, VERSION, CONF_DOMAIN, CONF_PROFILE, CONF_TYPE, CONF_SPEC) VALUES
('default-heatmap-chart-001', 'admin', now(), 'admin', now(), 0, 'CHART', 'tango', 'heatmap', '{"type":"heatmap","color":{"mode":"LINEAR","codes":["#1465c0","#e3f2fd"],"type":"measure"},"size":{"size":12},"label":{"showValue":true,"axis":[{"mode":"row","showName":false,"name":"","showMark":true,"mark":"HORIZONTAL"},{"mode":"column","showName":false,"name":"","showMark":true,"mark":"HORIZONTAL"}]},"legend":{"auto":false,"pos":"TOP"}}');
